project_id = "minlrvrnprwcrgqfgsws"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-split-order]
    verify_jwt = false
  [functions.send-email-unisender]
    verify_jwt = false
  [functions.subscribe-unisender]
    verify_jwt = false
  [functions.tbank-init-payment]
    verify_jwt = false
  [functions.tbank-webhook]
    verify_jwt = false
